### ISSUE TITLE
Updates not shown in mods.factorio portal

### ISSUE THREAD

**Issue by mike-kostov** [skandragon/skan-fusion-robots#1]
I am sorry If the lagging behind the mod portal is intentional, but my mega base depends on your mods and I was waiting for a couple of weeks before writting this issue.
Can't download via the mods browser in-game also I guess its related to the mods portal.

Also for:
https://github.com/skandragon/skan-advanced-solar
https://github.com/skandragon/skan-advanced-mining

**Comment by skandragon** [comment]
huh.  I'll look into it.
